
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 30259508
 */
public class FlowerShop extends javax.swing.JFrame {

    /**
     * Creates new form FlowerShop
     */
    public FlowerShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        tabOrders = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnQuantity8 = new javax.swing.JButton();
        btnQuantity9 = new javax.swing.JButton();
        btnQuantity0 = new javax.swing.JButton();
        btnQuantity1 = new javax.swing.JButton();
        btnQuantity2 = new javax.swing.JButton();
        btnQuantity3 = new javax.swing.JButton();
        btnQuantity4 = new javax.swing.JButton();
        btnQuantity5 = new javax.swing.JButton();
        btnQuantity6 = new javax.swing.JButton();
        btnQuantity7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnProduct1 = new javax.swing.JButton();
        btnProduct2 = new javax.swing.JButton();
        btnProduct3 = new javax.swing.JButton();
        btnProduct4 = new javax.swing.JButton();
        btnProduct5 = new javax.swing.JButton();
        btnProduct6 = new javax.swing.JButton();
        btnProduct7 = new javax.swing.JButton();
        btnProduct8 = new javax.swing.JButton();
        btnProduct9 = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listOrder = new javax.swing.JList<>();
        lblDisplayName = new javax.swing.JLabel();
        lblDisplayPrice = new javax.swing.JLabel();
        btnTester = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlCreateUser = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPinNumber = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox<>();
        txtUserName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        btnQuantity8.setText("8");
        btnQuantity8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity8ActionPerformed(evt);
            }
        });

        btnQuantity9.setText("9");
        btnQuantity9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity9ActionPerformed(evt);
            }
        });

        btnQuantity0.setText("0");
        btnQuantity0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity0ActionPerformed(evt);
            }
        });

        btnQuantity1.setText("1");
        btnQuantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity1ActionPerformed(evt);
            }
        });

        btnQuantity2.setText("2");
        btnQuantity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity2ActionPerformed(evt);
            }
        });

        btnQuantity3.setText("3");
        btnQuantity3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity3ActionPerformed(evt);
            }
        });

        btnQuantity4.setText("4");
        btnQuantity4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity4ActionPerformed(evt);
            }
        });

        btnQuantity5.setText("5");
        btnQuantity5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity5ActionPerformed(evt);
            }
        });

        btnQuantity6.setText("6");
        btnQuantity6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity6ActionPerformed(evt);
            }
        });

        btnQuantity7.setText("7");
        btnQuantity7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuantity0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuantity5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuantity6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity8)
                .addGap(18, 18, 18)
                .addComponent(btnQuantity9)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuantity0)
                    .addComponent(btnQuantity1)
                    .addComponent(btnQuantity2)
                    .addComponent(btnQuantity3)
                    .addComponent(btnQuantity4)
                    .addComponent(btnQuantity5)
                    .addComponent(btnQuantity6)
                    .addComponent(btnQuantity7)
                    .addComponent(btnQuantity8)
                    .addComponent(btnQuantity9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProduct1.setText("Product 1");
        btnProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct1ActionPerformed(evt);
            }
        });

        btnProduct2.setText("Product 2");
        btnProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct2ActionPerformed(evt);
            }
        });

        btnProduct3.setText("Product 3");

        btnProduct4.setText("Product 4");

        btnProduct5.setText("Product 5");

        btnProduct6.setText("Product 6");

        btnProduct7.setText("Product 7");

        btnProduct8.setText("Product 8");

        btnProduct9.setText("Product 9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPurchase.setText("Purchas");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        listOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listOrder);

        lblDisplayName.setText("lblDisplayName");

        lblDisplayPrice.setText("lblDisplayName");

        btnTester.setText("Test Button");
        btnTester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesterActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout tabOrdersLayout = new javax.swing.GroupLayout(tabOrders);
        tabOrders.setLayout(tabOrdersLayout);
        tabOrdersLayout.setHorizontalGroup(
            tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOrdersLayout.createSequentialGroup()
                .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisplayPrice)
                            .addComponent(lblDisplayName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTester)
                    .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tabOrdersLayout.createSequentialGroup()
                            .addComponent(btnPurchase)
                            .addGap(46, 46, 46)
                            .addComponent(btnClear))
                        .addComponent(jScrollPane2)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        tabOrdersLayout.setVerticalGroup(
            tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOrdersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPurchase)
                            .addComponent(btnClear))))
                .addGroup(tabOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblDisplayName)
                        .addGap(18, 18, 18)
                        .addComponent(lblDisplayPrice)
                        .addContainerGap())
                    .addGroup(tabOrdersLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabOrdersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTester)
                        .addGap(54, 54, 54))))
        );

        tabMain.addTab("tab1", tabOrders);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        tabMain.addTab("tab3", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        tabMain.addTab("tab4", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        tabMain.addTab("tab5", jPanel8);

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblUserName.setText("Username");

        lblPinNumber.setText("Pin Number");

        lblRole.setText("Role");

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Manager" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(lblLastName)
                            .addComponent(lblPinNumber)
                            .addComponent(lblRole)
                            .addComponent(btnCreateUser)
                            .addComponent(lblFirstName))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPinNumber)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCreateUser)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCreateUserLayout = new javax.swing.GroupLayout(pnlCreateUser);
        pnlCreateUser.setLayout(pnlCreateUserLayout);
        pnlCreateUserLayout.setHorizontalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        pnlCreateUserLayout.setVerticalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tabMain.addTab("Create User", pnlCreateUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuantity0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity0ActionPerformed

    private void btnQuantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity1ActionPerformed

    private void btnQuantity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity2ActionPerformed

    private void btnQuantity3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity3ActionPerformed

    private void btnQuantity4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity4ActionPerformed

    private void btnQuantity5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity5ActionPerformed

    private void btnQuantity6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity6ActionPerformed

    private void btnQuantity7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity7ActionPerformed

    private void btnQuantity8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity8ActionPerformed

    private void btnQuantity9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity9ActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPurchaseActionPerformed


    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checkTheLogin();
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // ********************** //
        
        User myUser = new User ();
        
        myUser.setFirstName(txtFirstName.getText());
        myUser.setLastName(txtLastName.getText());
        myUser.setUserName(txtUserName.getText());
        myUser.setPinNumber(Integer.parseInt(txtPassword.getText()));
        myUser.setRole((String)comboRole.getSelectedItem());
        
        Users_DATA_Handler myHandler =new Users_DATA_Handler();
        myHandler.insertUser(myUser);
        
        JOptionPane.showMessageDialog(this, "User Created");
        
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed
       
    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct2ActionPerformed

    private void btnTesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesterActionPerformed
       
        
    }//GEN-LAST:event_btnTesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlowerShop().setVisible(true);
            }
        });
    }
    
    public void checkTheLogin(){
    //programatically create the labels and texfields for the optionpane
    JLabel label_login = new JLabel("Username:");
    JTextField login = new JTextField();
    JLabel label_password = new JLabel("Password:");
    JPasswordField password = new JPasswordField();
 //-----------------------------------------------------
 // store these in an object array
 Object[] login_GUI_Elelemnts = { label_login, login, label_password, password };
 //-----------------------------------------------------
 int userInteraction = JOptionPane.showConfirmDialog(null, login_GUI_Elelemnts, "Login",
 JOptionPane.OK_CANCEL_OPTION,
 JOptionPane.PLAIN_MESSAGE);
// this integer variable 'userInteraction' will hold the result of
//the users interaction with the JOpttionPane
//we will then test the result against common returned values. OK OPtion , Cancel , Closed
//-----------------------------------------------------
 if (userInteraction == JOptionPane.OK_OPTION)
 {
 String user=login.getText().trim(); // user string that the user entered in the textfield
 String pass=new String(password.getPassword()); //pulls the password string from textfield
 Boolean entryGranted = false ;// setup boolean as false.
 //
 //
 //
 // !!!!!!!!!         You have to code this section       !!!!
 //
 //
 // 1) Setup a GLOBAL User variable  - Instantiate this user object then set the PIN Number and Username fields of the object using the setters 
 // 2) Instantiate a Users Data handler and call its method CheckUserIsValid - this returns a boolean
 //    if you receieve a TRUE then you have a valid user. 
 // 3) Once you have a valid user you can then use the method getValidUser of the DB Handler.- this returns a FULL VALID USER
 //
 
 
 User theUser = new User(); // INSTANTIATES TEH OBJECT
 theUser.setPinNumber(Integer.parseInt(pass));
 theUser.setUserName(user);
 
 System.out.println("The users data is now: " + theUser.toString());
 
 Users_DATA_Handler myUsersHandler = new Users_DATA_Handler();
 
 if (myUsersHandler.checkUserIsValid(theUser)){
     theUser = myUsersHandler.getValidUser(theUser);
 
 
 System.out.println("Equals: " + theUser.toString());
         }
 
         
// if (( user.toUpperCase().equals ("U")) && pass.toUpperCase().equals ("2")) // this line will change 
 // if users role is USER then....
 
  if (theUser.getRole().toUpperCase().equals("USER"))
    {
    JOptionPane.showMessageDialog(this, "Logged in as user\nAdmin panel will be removed");
       //If an ordinary user logged in then remove the panel tabs that relate to administrators.
       
       this.tabOrders.remove(tabMain); //removes the user crud tab
       this.tabOrders.remove(pnlCreateUser);
       entryGranted=true;
    }
 
 
 //if (( user.toUpperCase().equals ("M")) && pass.toUpperCase().equals ("1")) // this line will change
  // if users role is Manager then....
    
  if (theUser.getRole().toUpperCase().equals("MANAGER"))
  {
    JOptionPane.showMessageDialog(this, "Logged in as manager\nAccess granted to all areas");
    entryGranted=true;
    }
  
  
  
  
  
  
  
  
  
 if (!entryGranted) //entry denied
    {
    JOptionPane.showMessageDialog(this, "Go chase yourself - entry denied");
    userInteraction = JOptionPane.CANCEL_OPTION;
    }
 }
 
else
    {//user clicked on CANCEL or the X close button- we change the userInteraction to force execution of the CANCEL block of code
    userInteraction = JOptionPane.CANCEL_OPTION;
    }
 
 
 
 
 
 
 if ( (userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION) )
 // the cancel block of code - if user presses the X or CANCEL
    {
    //feedback to user and close the application as no suitable login credentials have been supplied.
    JOptionPane.showMessageDialog(this, "You have not supplied valid credentials\n the application will now terminate");
    System.exit(0);
    } 
 } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnProduct2;
    private javax.swing.JButton btnProduct3;
    private javax.swing.JButton btnProduct4;
    private javax.swing.JButton btnProduct5;
    private javax.swing.JButton btnProduct6;
    private javax.swing.JButton btnProduct7;
    private javax.swing.JButton btnProduct8;
    private javax.swing.JButton btnProduct9;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnQuantity0;
    private javax.swing.JButton btnQuantity1;
    private javax.swing.JButton btnQuantity2;
    private javax.swing.JButton btnQuantity3;
    private javax.swing.JButton btnQuantity4;
    private javax.swing.JButton btnQuantity5;
    private javax.swing.JButton btnQuantity6;
    private javax.swing.JButton btnQuantity7;
    private javax.swing.JButton btnQuantity8;
    private javax.swing.JButton btnQuantity9;
    private javax.swing.JButton btnTester;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblDisplayPrice;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPinNumber;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JList<String> listOrder;
    private javax.swing.JPanel pnlCreateUser;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabOrders;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
